// frameworks/next/app/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { cvData, getSkillIcon } from './data'

export default function HomePage() {
  const [mounted, setMounted] = useState(false)
  const [theme, setTheme] = useState<'light' | 'dark'>('dark')
  const [lang, setLang] = useState<'es' | 'en'>('es')
  const [formStatus, setFormStatus] = useState<'idle' | 'sending' | 'success' | 'error'>('idle')
  const [activeCategory, setActiveCategory] = useState('Todos')

  useEffect(() => {
    setMounted(true)
    const savedTheme = localStorage.getItem('theme') as 'light' | 'dark' | null
    const savedLang = localStorage.getItem('lang') as 'es' | 'en' | null
    if (savedTheme) {
      setTheme(savedTheme)
      document.body.classList.toggle('light', savedTheme === 'light')
    }
    if (savedLang) setLang(savedLang)

    // Load EmailJS SDK
    const script = document.createElement('script')
    script.src = 'https://cdn.jsdelivr.net/npm/@emailjs/browser@4/dist/email.min.js'
    script.async = true
    script.onload = () => {
      // Initialize EmailJS with correct publicKey (same as React/Astro)
      // @ts-ignore
      if (window.emailjs) {
        // @ts-ignore
        window.emailjs.init({ publicKey: 'qZw7aS4i2gCI3Wz2B' })
      }
    }
    document.head.appendChild(script)
  }, [])

  const toggleTheme = () => {
    const newTheme = theme === 'dark' ? 'light' : 'dark'
    setTheme(newTheme)
    localStorage.setItem('theme', newTheme)
    document.body.classList.toggle('light', newTheme === 'light')
  }

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    setFormStatus('sending')
    
    const form = e.currentTarget
    
    try {
      // @ts-ignore
      if (!window.emailjs) {
        throw new Error('EmailJS not loaded')
      }
      
      // Use sendForm() like React and Astro versions with CORRECT credentials
      // @ts-ignore
      await window.emailjs.sendForm(
        'service_35dui0c',
        'template_dlh2p8t',
        form,
        'qZw7aS4i2gCI3Wz2B'
      )
      setFormStatus('success')
      form.reset()
      setTimeout(() => setFormStatus('idle'), 5000)
    } catch (error) {
      console.error('EmailJS error:', error)
      setFormStatus('error')
      setTimeout(() => setFormStatus('idle'), 5000)
    }
  }

  if (!mounted) return null

  const t = (es: string, en: string) => (lang === 'es' ? es : en)

  const frameworks = [
    { id: 'react', name: 'React', icon: '⚛️', url: '/' },
    { id: 'astro', name: 'Astro', icon: '🪐', url: '/astro/' },
    { id: 'vue', name: 'Vue', icon: '💚', url: '/vue/' },
    { id: 'solid', name: 'Solid', icon: '🔷', url: '/solid/' },
    { id: 'vanilla', name: 'Vanilla', icon: '⚡', url: '/vanilla/' },
    { id: 'next', name: 'Next.js', icon: '▲', url: '/next/', active: true },
    { id: 'lab', name: 'Lab', icon: '🧪', url: '/lab/' },
  ]

  const { personal, about, experience, education, projects, skills, services } = cvData

  // Filtros de proyectos
  const FULLSTACK_KEYS = ['Django','Python','Node.js','Express','Ruby on Rails','PostgreSQL','JWT','Celery','Redis','Nuxt.js']
  const getCategory = (p: any) => {
    if (p.category) return p.category
    const tech = p.technologies || []
    if (tech.includes('WordPress') || tech.includes('WooCommerce')) return 'WordPress'
    const isFull = FULLSTACK_KEYS.some(t => tech.includes(t))
    return isFull ? 'Full Stack' : 'Personal'
  }
  
  const categories = ['Todos', 'Full Stack', 'WordPress', 'Personal']
  const filteredProjects = activeCategory === 'Todos' 
    ? projects 
    : projects.filter((p: any) => getCategory(p) === activeCategory)

  return (
    <>
      {/* Navbar idéntico a Astro */}
      <nav>
        <div className="inner">
          {/* Fila 1: Menu principal */}
          <div className="menu-row">
            <button
              className="logo-btn"
              onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
              title="Volver arriba"
            >
              👨‍💻
            </button>
            <div className="menu-links">
              <a href="#about">
                <span className="icon">👤</span>
                <span>{t('Sobre mí', 'About')}</span>
              </a>
              <a href="#services">
                <span className="icon">🚀</span>
                <span>{t('Servicios', 'Services')}</span>
              </a>
              <a href="#experience">
                <span className="icon">💼</span>
                <span>{t('Experiencia', 'Experience')}</span>
              </a>
              <a href="#education">
                <span className="icon">🎓</span>
                <span>{t('Educación', 'Education')}</span>
              </a>
              <a href="#projects">
                <span className="icon">🎨</span>
                <span>{t('Proyectos', 'Projects')}</span>
              </a>
              <a href="#skills">
                <span className="icon">⚡</span>
                <span>{t('Habilidades', 'Skills')}</span>
              </a>
              <a href="#contact">
                <span className="icon">📧</span>
                <span>{t('Contacto', 'Contact')}</span>
              </a>
            </div>
            <div className="controls">
              <button className="theme-toggle" onClick={toggleTheme} title="Toggle theme">
                <span>{theme === 'dark' ? '🌙' : '☀️'}</span>
              </button>
              <div className="lang-toggle">
                <button
                  className={lang === 'es' ? 'active' : ''}
                  onClick={() => { setLang('es'); localStorage.setItem('lang', 'es'); }}
                >
                  ES
                </button>
                <button
                  className={lang === 'en' ? 'active' : ''}
                  onClick={() => { setLang('en'); localStorage.setItem('lang', 'en'); }}
                >
                  EN
                </button>
              </div>
            </div>
          </div>

          {/* Fila 2: Framework switcher */}
          <div className="frameworks-row">
            {frameworks.map((fw) => (
              <a
                key={fw.id}
                href={fw.url}
                className={fw.active ? 'active' : ''}
                title={`Ver en ${fw.name}`}
              >
                {fw.icon} <span className="hidden-mobile">{fw.name}</span>
              </a>
            ))}
          </div>
        </div>
      </nav>

      <div className="container">
        {/* Hero */}
        <section className="panel">
          <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem', flexWrap: 'wrap' }}>
            <img 
              src="/favicon.ico" 
              alt={personal.name}
              style={{ width: '90px', height: '90px', borderRadius: '18px', objectFit: 'cover', boxShadow: '0 4px 12px rgba(0,0,0,0.3)' }}
            />
            <div style={{ flex: 1 }}>
              <h1>{t('Hola, soy', 'Hi, I\'m')} {personal.name}</h1>
              <small>{personal.location}</small>
            </div>
          </div>
          <p style={{ marginTop: '1rem' }}>
            {t(
              'Desarrollador Full-Stack. Aquí tienes mi CV en PDF listo para descargar.',
              'Full-Stack Developer. Here\'s my resume in PDF ready to download.'
            )}
          </p>
          <div style={{ marginTop: '1.25rem' }}>
            <a href="/CV-Eduardo-Valenzuela.pdf" className="btn" download>
              {t('📄 Descargar CV', '📄 Download Resume')}
            </a>
            <a href="#contact" className="btn secondary" style={{ marginLeft: '0.75rem' }}>
              {t('💬 Contacto', '💬 Contact')}
            </a>
          </div>
        </section>

        {/* About */}
        <section id="about" className="panel">
          <h2>👨‍💻 {t('Sobre mí', 'About Me')}</h2>
          <div style={{ whiteSpace: 'pre-wrap' }}>
            {lang === 'es' ? about.es : about.en}
          </div>
        </section>

        {/* Services */}
        <section id="services">
          <h2 style={{ textAlign: 'center', marginBottom: '2rem' }}>
            🚀 {t('Servicios', 'Services')}
          </h2>
          <div className="grid-2">
            {services.map((service: any, idx: number) => (
              <div key={idx} className="service">
                <div className="icon-box">{service.icon}</div>
                <h3>{lang === 'es' ? service.titleES : service.titleEN}</h3>
                <p>{lang === 'es' ? service.descES : service.descEN}</p>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                  {service.tags.map((tag: string) => (
                    <span key={tag} className="badge">{tag}</span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Experience */}
        <section id="experience">
          <h2 style={{ textAlign: 'center', marginBottom: '2rem' }}>
            💼 {t('Experiencia', 'Experience')}
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            {experience.map((exp: any, idx: number) => (
              <div key={idx} className="exp-card">
                <div style={{ display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', gap: '0.5rem', marginBottom: '0.75rem' }}>
                  <div>
                    <h3>{exp.company}</h3>
                    <p style={{ margin: '0.25rem 0', fontSize: '0.95rem', fontWeight: 500 }}>{exp.position}</p>
                  </div>
                  <div style={{ textAlign: 'right' }}>
                    <small style={{ display: 'block' }}>{exp.period}</small>
                    <small>{exp.location}</small>
                  </div>
                </div>
                <p>{exp.description}</p>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginTop: '1rem' }}>
                  {exp.technologies.map((tech: string) => (
                    <span key={tech} className="badge">{tech}</span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Education */}
        <section id="education">
          <h2 style={{ textAlign: 'center', marginBottom: '2rem' }}>
            🎓 {t('Educación y Certificaciones', 'Education & Certifications')}
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            {education.map((edu: any, idx: number) => (
              <div key={idx} className="exp-card" style={{ borderLeft: '4px solid var(--primary)', paddingLeft: '1.5rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', gap: '0.5rem', marginBottom: '0.75rem' }}>
                  <div style={{ flex: 1 }}>
                    <h3>{edu.degree}</h3>
                    <small style={{ color: 'var(--primary)', fontWeight: 600 }}>{edu.institution}</small>
                  </div>
                  <span style={{ fontSize: '0.875rem', color: 'var(--text-muted)', whiteSpace: 'nowrap' }}>{edu.period}</span>
                </div>
                <p>{edu.description}</p>
                {edu.skills && (
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginTop: '1rem' }}>
                    {edu.skills.map((skill: string) => (
                      <span key={skill} className="badge">{skill}</span>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* Projects */}
        <section id="projects">
          <h2 style={{ textAlign: 'center', marginBottom: '1rem' }}>
            🎨 {t('Proyectos', 'Projects')}
          </h2>
          <div style={{ display: 'flex', justifyContent: 'center', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '2rem' }}>
            {categories.map(cat => (
              <button
                key={cat}
                onClick={() => setActiveCategory(cat)}
                className={`badge ${activeCategory === cat ? 'active' : ''}`}
                style={{ 
                  cursor: 'pointer',
                  ...(activeCategory === cat && { background: '#3b82f6', color: 'white' })
                }}
              >
                {cat}
              </button>
            ))}
          </div>
          <div className="grid">
            {filteredProjects.map((project: any, idx: number) => (
              <div key={idx} className="proj-card">
                <h3>{project.name}</h3>
                <p style={{ fontSize: '0.9rem', margin: '0.75rem 0' }}>{project.description}</p>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginTop: '1rem' }}>
                  {project.technologies.map((tech: string) => (
                    <span key={tech} className="badge">{tech}</span>
                  ))}
                </div>
                {project.link && (
                  <div style={{ marginTop: '1rem' }}>
                    <a href={project.link} target="_blank" rel="noopener noreferrer" className="btn" style={{ fontSize: '0.85rem', padding: '0.5rem 0.9rem' }}>
                      {t('Ver proyecto', 'View project')} →
                    </a>
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* Skills */}
        <section id="skills">
          <h2 style={{ textAlign: 'center', marginBottom: '2rem' }}>
            ⚡ {t('Habilidades', 'Skills')}
          </h2>
          <div className="grid-skills">
            {Object.entries(skills).map(([category, skillList]: [string, any]) => (
              <div key={category} className="panel">
                <h3 style={{ marginBottom: '1rem' }}>{category}</h3>
                <div className="skills-badges">
                  {skillList.map((skill: string) => (
                    <span key={skill} className="badge" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                      <span dangerouslySetInnerHTML={{ __html: getSkillIcon(skill) }} />
                      {skill}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Contact */}
        <section id="contact">
          <h2 style={{ textAlign: 'center', marginBottom: '2rem' }}>
            📧 {t('Contacto', 'Contact')}
          </h2>
          <div className="grid-2">
            <div className="panel">
              <h3 style={{ marginBottom: '1.25rem' }}>{t('Información de contacto', 'Contact Information')}</h3>
              <ul className="contact-info">
                <li>
                  <span className="icon">📧</span>
                  <div className="detail">
                    <strong>{t('Email', 'Email')}</strong>
                    <a href={`mailto:${personal.email}`}>{personal.email}</a>
                  </div>
                </li>
                <li>
                  <span className="icon">📱</span>
                  <div className="detail">
                    <strong>{t('Teléfono', 'Phone')}</strong>
                    <a href={`tel:${personal.phone}`}>{personal.phone}</a>
                  </div>
                </li>
                <li>
                  <span className="icon">🐱</span>
                  <div className="detail">
                    <strong>GitHub</strong>
                    <a href={`https://github.com/${personal.social.github}`} target="_blank" rel="noopener noreferrer">
                      github.com/{personal.social.github}
                    </a>
                  </div>
                </li>
                <li>
                  <span className="icon">💼</span>
                  <div className="detail">
                    <strong>LinkedIn</strong>
                    <a href={`https://linkedin.com/in/${personal.social.linkedin}`} target="_blank" rel="noopener noreferrer">
                      linkedin.com/in/{personal.social.linkedin}
                    </a>
                  </div>
                </li>
              </ul>
            </div>

            <div className="panel">
              <h3 style={{ marginBottom: '1.25rem' }}>{t('Envíame un mensaje', 'Send me a message')}</h3>
              <form onSubmit={handleSubmit}>
                <div className="field">
                  <label className="label">{t('Nombre', 'Name')}</label>
                  <input type="text" name="from_name" className="input" required />
                </div>
                <div className="field">
                  <label className="label">{t('Email', 'Email')}</label>
                  <input type="email" name="from_email" className="input" required />
                </div>
                <div className="field">
                  <label className="label">{t('Mensaje', 'Message')}</label>
                  <textarea name="message" className="textarea" required></textarea>
                </div>
                <button type="submit" className="btn" disabled={formStatus === 'sending'}>
                  {formStatus === 'sending' 
                    ? t('Enviando...', 'Sending...') 
                    : t('Enviar mensaje', 'Send message')}
                </button>
                {formStatus === 'success' && (
                  <div className="alert success" style={{ marginTop: '1rem' }}>
                    {t('¡Mensaje enviado con éxito!', 'Message sent successfully!')}
                  </div>
                )}
                {formStatus === 'error' && (
                  <div className="alert error" style={{ marginTop: '1rem' }}>
                    {t('Error al enviar el mensaje. Intenta de nuevo.', 'Error sending message. Try again.')}
                  </div>
                )}
              </form>
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer style={{ textAlign: 'center', padding: '2rem 0', color: '#64748b', fontSize: '0.85rem' }}>
          <p>© 2025 {personal.name} — {t('Hecho con', 'Built with')} ▲ Next.js</p>
        </footer>
      </div>
    </>
  )
}

// frameworks/solid/src/App.jsx
import { createSignal, onMount, For, Show } from 'solid-js';
import Navbar from './components/Navbar';
import cvData from '@data/cv-data.json';
import emailjs from '@emailjs/browser';

const services = [
  {
    icon: '🛠️',
    titleES: 'Desarrollo Web & Apps',
    titleEN: 'Web & App Development',
    descES: 'Sitios web corporativos, e-commerce, landing pages y aplicaciones web full-stack con React, Django, Rails y WordPress.',
    descEN: 'Corporate websites, e-commerce, landing pages and full-stack web applications with React, Django, Rails and WordPress.',
    tags: ['React', 'WordPress', 'Django', 'E-Commerce', 'SaaS']
  },
  {
    icon: '🔍',
    titleES: 'Auditorías SEO',
    titleEN: 'SEO Audits',
    descES: 'Análisis técnico completo de SEO on-page, velocidad de carga, estructura del sitio y Core Web Vitals.',
    descEN: 'Complete technical SEO on-page analysis, page speed, site structure and Core Web Vitals.',
    tags: ['SEO On-Page', 'PageSpeed', 'Analytics', 'SEMrush']
  },
  {
    icon: '🤖',
    titleES: 'Asistentes IA Personalizados',
    titleEN: 'Custom AI Assistants',
    descES: 'Diseño e integración de chatbots inteligentes con ChatGPT, Claude AI y modelos custom para automatización.',
    descEN: 'Design and integration of intelligent chatbots with ChatGPT, Claude AI and custom models for automation.',
    tags: ['ChatGPT', 'Claude AI', 'Automation', 'Webhooks']
  },
  {
    icon: '🔌',
    titleES: 'Integraciones & Plugins',
    titleEN: 'Integrations & Plugins',
    descES: 'Desarrollo de plugins WordPress personalizados, conexiones con APIs externas y pasarelas de pago.',
    descEN: 'Custom WordPress plugin development, external API connections and payment gateways.',
    tags: ['WordPress Plugins', 'APIs', 'Google Drive', 'Webhooks']
  }
];

// Iconos para skills
const SKILL_ICONS = {
  'HTML': '🌐', 'CSS': '🎨', 'JavaScript': '⚡', 'JavaScript/ES6+': '⚡',
  'TypeScript': '📘', 'React': '⚛️', 'React.js': '⚛️', 'Vue.js': '💚',
  'Angular': '🅰️', 'Tailwind CSS': '🎨', 'Bootstrap': '🅱️',
  'WordPress': '📰', 'Shopify': '🛒', 'Node.js': '🟢', 'Express': '⚡',
  'Python': '🐍', 'Django': '🎸', 'Flask': '🔶', 'Ruby on Rails': '💎',
  'Ruby': '💎', 'PHP': '🐘', 'PostgreSQL': '🐘', 'MySQL': '🐬',
  'MongoDB': '🍃', 'Git': '🔀', 'Docker': '🐳', 'ChatGPT': '🤖',
  'GitHub Copilot': '🤖', 'GitHub': '🐱', 'Google Gemini': '✨',
  'Jira': '📋', 'Trello': '📋', 'Postman': '📮', 'SEMrush': '📊',
  'Wix': '🌐', 'Google Analytics': '📊', 'Google Search Console': '🔍',
  'PageSpeed Insights': '⚡', 'Vercel': '▲', 'Render': '🚀',
  'Railway': '🚂', 'Heroku': '🟣', 'REST API': '🔗', 'REST APIs': '🔗',
  'SEO': '🔍', 'SEO Audits': '🧪', 'Yii Framework': '🎴',
  'Zoho CRM': '📇', 'AWS': '☁️', 'Claude AI': '🤖', 'Loveable AI': '💖',
  'Monday': '📋', 'HTML/CSS': '🎨', 'Google Trends': '📈',
  'Asistentes IA Personalizados': '🛠️', 'Grok': '🤖', 'Beaver Builder': '🦫'
};
const getSkillIcon = (name) => SKILL_ICONS[name] || '';

function App() {
  const [currentLang, setCurrentLang] = createSignal('es');
  const [theme, setTheme] = createSignal('dark');
  const [formData, setFormData] = createSignal({ name: '', email: '', message: '' });
  const [formStatus, setFormStatus] = createSignal(null);
  const [formLoading, setFormLoading] = createSignal(false);

  // Filtros de proyectos (igual a React)
  const FULLSTACK_KEYS = ['Django','Python','Node.js','Express','Ruby on Rails','PostgreSQL','JWT','Celery','Redis','Nuxt.js'];
  const getCategory = (p) => {
    if (p.category) return p.category;
    const tech = p.technologies || [];
    if (tech.includes('WordPress') || tech.includes('WooCommerce')) return 'WordPress';
    const isFull = FULLSTACK_KEYS.some(t => tech.includes(t));
    return isFull ? 'Full Stack' : 'Personal';
  };
  const categoryIcons = { 'Todos': '🗂️', 'WordPress': '🧩', 'Full Stack': '🧰', 'Personal': '⭐' };
  const categories = ['Todos','Full Stack','WordPress','Personal'].filter(k => {
    if (k === 'Todos') return cvData.projects.length > 0;
    return cvData.projects.some(p => getCategory(p) === k);
  });
  const [selectedCategory, setSelectedCategory] = createSignal('Todos');
  const filteredProjects = () => {
    const sel = selectedCategory();
    const list = sel === 'Todos' ? cvData.projects : cvData.projects.filter(p => getCategory(p) === sel);
    const priority = { 'Full Stack': 0, 'WordPress': 1, 'Personal': 2 };
    return [...list].sort((a,b) => {
      if (sel === 'Todos') {
        const pa = priority[getCategory(a)] ?? 99; const pb = priority[getCategory(b)] ?? 99;
        if (pa !== pb) return pa - pb;
      }
      return Number(b.featured) - Number(a.featured);
    });
  };
  const countFor = (cat) => cat === 'Todos' ? cvData.projects.length : cvData.projects.filter(p => getCategory(p) === cat).length;

  const aboutParagraphs = () => {
    const text = currentLang() === 'es' ? (cvData.about?.es || '') : (cvData.about?.en || '');
    return text.split('\n\n');
  };

  const handleLangChange = (lang) => {
    setCurrentLang(lang);
    localStorage.setItem('solid-lang', lang);
  };

  const handleThemeToggle = () => {
    const newTheme = theme() === 'dark' ? 'light' : 'dark';
    setTheme(newTheme);
    localStorage.setItem('solid-theme', newTheme);
    document.body.classList.toggle('light', newTheme === 'light');
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setFormLoading(true);
    setFormStatus(null);

    try {
      const result = await emailjs.send(
        'service_35dui0c',
        'template_dlh2p8t',
        {
          from_name: formData().name,
          from_email: formData().email,
          message: formData().message
        },
        'qZw7aS4i2gCI3Wz2B'
      );

      if (result.text === 'OK') {
        setFormStatus({
          type: 'success',
          message: currentLang() === 'es' 
            ? '¡Mensaje enviado! Te responderé pronto 🚀' 
            : 'Message sent! I\'ll reply soon 🚀'
        });
        setFormData({ name: '', email: '', message: '' });
      } else {
        throw new Error('EmailJS error');
      }
    } catch (error) {
      console.error('EmailJS error:', error);
      setFormStatus({
        type: 'error',
        message: currentLang() === 'es'
          ? 'Hubo un error al enviar. Intenta nuevamente.'
          : 'There was an error sending. Please try again.'
      });
    } finally {
      setFormLoading(false);
    }
  };

  onMount(() => {
    const savedLang = localStorage.getItem('solid-lang') || 'es';
    setCurrentLang(savedLang);

    const savedTheme = localStorage.getItem('solid-theme') || 'dark';
    setTheme(savedTheme);
    document.body.classList.toggle('light', savedTheme === 'light');

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('visible');
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.1 }
    );

    document.querySelectorAll('.reveal').forEach((el) => observer.observe(el));
  });

  return (
    <>
      <Navbar 
        currentLang={currentLang()} 
        theme={theme()} 
        onChangeLang={handleLangChange}
        onToggleTheme={handleThemeToggle}
      />

      <main class="container">
        {/* Hero */}
        <section class="panel reveal">
          <div style={{ display: 'flex', 'align-items': 'center', gap: '1.5rem', 'flex-wrap': 'wrap' }}>
            <img src="/favicon.ico" alt="Eduardo Valenzuela" style={{ width: '90px', height: '90px', 'border-radius': '18px', 'object-fit': 'cover', 'flex-shrink': '0', 'box-shadow': '0 4px 12px rgba(0,0,0,.3)' }} />
            <div style={{ flex: 1 }}>
              <h1>{currentLang() === 'es' ? `Hola, soy ${cvData.personal.name}` : `Hi, I'm ${cvData.personal.name}`}</h1>
              <small>{cvData.personal.location}</small>
            </div>
          </div>
          <p style={{ 'margin-top': '1rem' }}>
            {currentLang() === 'es' ? 'Desarrollador Full‑Stack. Aquí tienes mi CV en PDF listo para descargar.' : 'Full‑Stack Developer. Here\'s my resume in PDF ready to download.'}
          </p>
          <p style={{ 'margin-top': '1.25rem' }}>
            <a class="btn" href="/CV-Eduardo-Valenzuela.pdf" download>
              {currentLang() === 'es' ? '📄 Descargar CV' : '📄 Download Resume'}
            </a>
            <a class="btn secondary" href="#contact" style={{ 'margin-left': '0.75rem' }}>
              {currentLang() === 'es' ? '💬 Contacto' : '💬 Contact'}
            </a>
          </p>
        </section>

        {/* About */}
        <section id="about" class="panel reveal">
          <h2>
            <span>👨‍💻</span>
            <span>{currentLang() === 'es' ? 'Sobre mí' : 'About Me'}</span>
          </h2>
          <For each={aboutParagraphs()}>
            {(paragraph) => <p>{paragraph}</p>}
          </For>
        </section>

        {/* Services */}
        <section id="services" class="panel reveal">
          <div style={{ 'text-align': 'center', 'max-width': '650px', margin: '0 auto 2rem' }}>
            <h2 style={{ 'justify-content': 'center' }}>
              <span>🚀</span>
              <span>{currentLang() === 'es' ? 'Servicios' : 'Services'}</span>
            </h2>
            <p style={{ color: '#94a3b8', 'font-size': '0.95rem' }}>
              {currentLang() === 'es' ? 'Soluciones digitales completas para hacer crecer tu negocio' : 'Complete digital solutions to grow your business'}
            </p>
          </div>
          <div class="grid-2">
            <For each={services}>
              {(service) => (
                <div class="service">
                  <div class="icon-box">{service.icon}</div>
                  <h3>{currentLang() === 'es' ? service.titleES : service.titleEN}</h3>
                  <p>{currentLang() === 'es' ? service.descES : service.descEN}</p>
                  <div style={{ display: 'flex', 'flex-wrap': 'wrap', gap: '0.5rem', 'margin-top': '1rem' }}>
                    <For each={service.tags}>
                      {(tag) => <span class="badge">{tag}</span>}
                    </For>
                  </div>
                </div>
              )}
            </For>
          </div>
        </section>

        {/* Experience */}
        <section id="experience" class="panel reveal">
          <h2>
            <span>💼</span>
            <span>{currentLang() === 'es' ? 'Experiencia' : 'Experience'}</span>
          </h2>
          <div class="grid-2">
            <For each={cvData.experience}>
              {(exp) => (
                <div class="exp-card">
                  <h3>{exp.position}</h3>
                  <small>{exp.company} • {exp.period}</small>
                  <p>{exp.description}</p>
                  <div style={{ display: 'flex', 'flex-wrap': 'wrap', gap: '0.5rem', 'margin-top': '1rem' }}>
                    <For each={exp.technologies}>
                      {(tech) => <span class="badge">{tech}</span>}
                    </For>
                  </div>
                </div>
              )}
            </For>
          </div>
        </section>

        {/* Education */}
        <section id="education" class="panel reveal">
          <h2>
            <span>🎓</span>
            <span>{currentLang() === 'es' ? 'Educación y Certificaciones' : 'Education & Certifications'}</span>
          </h2>
          <div style={{ display: 'flex', 'flex-direction': 'column', gap: '1.5rem' }}>
            <For each={cvData.education}>
              {(edu) => (
                <div class="exp-card" style={{ 'border-left': '4px solid var(--primary)', 'padding-left': '1.5rem' }}>
                  <div style={{ display: 'flex', 'justify-content': 'space-between', 'align-items': 'start', gap: '1rem', 'flex-wrap': 'wrap', 'margin-bottom': '0.5rem' }}>
                    <div style={{ flex: 1 }}>
                      <h3>{edu.degree}</h3>
                      <small style={{ color: 'var(--primary)', 'font-weight': 600 }}>{edu.institution}</small>
                    </div>
                    <span style={{ 'font-size': '0.875rem', color: 'var(--text-muted)', 'white-space': 'nowrap' }}>{edu.period}</span>
                  </div>
                  <p>{edu.description}</p>
                </div>
              )}
            </For>
          </div>
        </section>

        {/* Projects */}
        <section id="projects" class="panel reveal">
          <h2>
            <span>🎨</span>
            <span>{currentLang() === 'es' ? 'Proyectos Destacados' : 'Featured Projects'}</span>
          </h2>
          <div class="panel" style={{ padding: '.5rem .75rem', 'margin-bottom': '1rem' }}>
            <div style={{ display: 'flex', 'flex-wrap': 'wrap', gap: '.5rem' }}>
              <For each={categories}>
                {(cat) => (
                  <button
                    class={`badge ${selectedCategory() === cat ? 'active' : ''}`}
                    aria-selected={selectedCategory() === cat}
                    onClick={() => setSelectedCategory(cat)}
                  >
                    <span style={{ 'margin-right': '.35rem' }}>{categoryIcons[cat] || '🏷️'}</span>
                    {cat}
                    <span style={{ 'margin-left': '.5rem', opacity: 0.8 }}>{countFor(cat)}</span>
                  </button>
                )}
              </For>
            </div>
          </div>
          <div class="grid">
            <For each={filteredProjects()}>
              {(proj) => (
                <div class="proj-card">
                  <h3>{proj.name}</h3>
                  <small>{proj.year}</small>
                  <p>{proj.description}</p>
                  <div style={{ display: 'flex', 'flex-wrap': 'wrap', gap: '0.5rem', 'margin-top': '0.75rem' }}>
                    <For each={proj.technologies}>
                      {(tech) => <span class="badge">{tech}</span>}
                    </For>
                  </div>
                  <div style={{ display: 'flex', gap: '0.75rem', 'margin-top': '1rem', 'flex-wrap': 'wrap' }}>
                    <Show when={proj.demo}>
                      <a href={proj.demo} target="_blank" rel="noopener" class="btn" style={{ padding: '0.5rem 0.9rem', 'font-size': '0.85rem' }}>
                        {currentLang() === 'es' ? '🌐 Ver Demo' : '🌐 View Demo'}
                      </a>
                    </Show>
                    <Show when={proj.github}>
                      <a href={proj.github} target="_blank" rel="noopener" class="btn secondary" style={{ padding: '0.5rem 0.9rem', 'font-size': '0.85rem' }}>
                        {currentLang() === 'es' ? '💻 Código' : '💻 Code'}
                      </a>
                    </Show>
                  </div>
                </div>
              )}
            </For>
          </div>
        </section>

        {/* Skills */}
        <section id="skills" class="panel reveal">
          <h2>
            <span>⚡</span>
            <span>{currentLang() === 'es' ? 'Habilidades' : 'Skills'}</span>
          </h2>
          <div class="grid-skills">
            <article class="panel">
              <h3>Frontend</h3>
              <div class="badges" style={{ 'margin-top': '.75rem' }}>
                <For each={cvData.skills.frontend}>{(s) => <span class="badge" title={`${s.level}%`}>{getSkillIcon(s.name) && <span style={{ 'margin-right': '4px' }}>{getSkillIcon(s.name)}</span>}{s.name}</span>}</For>
              </div>
            </article>
            <article class="panel">
              <h3>Backend</h3>
              <div class="badges" style={{ 'margin-top': '.75rem' }}>
                <For each={cvData.skills.backend}>{(s) => <span class="badge" title={`${s.level}%`}>{getSkillIcon(s.name) && <span style={{ 'margin-right': '4px' }}>{getSkillIcon(s.name)}</span>}{s.name}</span>}</For>
              </div>
            </article>
            <article class="panel">
              <h3>{currentLang() === 'es' ? 'Herramientas · Bases de datos' : 'Tools · Databases'}</h3>
              <div class="badges" style={{ 'margin-top': '.75rem' }}>
                <For each={cvData.skills.tools.databases}>{(s) => <span class="badge" title={`${s.level}%`}>{getSkillIcon(s.name) && <span style={{ 'margin-right': '4px' }}>{getSkillIcon(s.name)}</span>}{s.name}</span>}</For>
              </div>
            </article>
            <article class="panel">
              <h3>SEO & Analytics</h3>
              <div class="badges" style={{ 'margin-top': '.75rem' }}>
                <For each={cvData.skills.tools.seoAnalytics}>{(s) => <span class="badge" title={`${s.level}%`}>{getSkillIcon(s.name) && <span style={{ 'margin-right': '4px' }}>{getSkillIcon(s.name)}</span>}{s.name}</span>}</For>
              </div>
            </article>
            <article class="panel">
              <h3>{currentLang() === 'es' ? 'Herramientas · Dev & Deploy' : 'Tools · Dev & Deploy'}</h3>
              <div class="badges" style={{ 'margin-top': '.75rem' }}>
                <For each={cvData.skills.tools.devTools}>{(s) => <span class="badge" title={`${s.level}%`}>{getSkillIcon(s.name) && <span style={{ 'margin-right': '4px' }}>{getSkillIcon(s.name)}</span>}{s.name}</span>}</For>
              </div>
            </article>
            <article class="panel">
              <h3>IA</h3>
              <div class="badges" style={{ 'margin-top': '.75rem' }}>
                <For each={cvData.skills.ai}>{(s) => <span class="badge" title={`${s.level}%`}>{getSkillIcon(s.name) && <span style={{ 'margin-right': '4px' }}>{getSkillIcon(s.name)}</span>}{s.name}</span>}</For>
              </div>
            </article>
          </div>
        </section>

        {/* Contact */}
        <section id="contact" class="panel reveal">
          <h2>
            <span>📧</span>
            <span>{currentLang() === 'es' ? 'Contacto' : 'Contact'}</span>
          </h2>
          <div class="grid-2">
            <div>
              <h3 style={{ 'margin-bottom': '1rem' }}>{currentLang() === 'es' ? '¿Hablamos?' : 'Let\'s talk?'}</h3>
              <p>{currentLang() === 'es' ? 'Si tienes un proyecto en mente o simplemente quieres conversar sobre tecnología, envíame un mensaje.' : 'If you have a project in mind or just want to chat about technology, send me a message.'}</p>
              <ul class="contact-info">
                <li>
                  <span class="icon">📧</span>
                  <div class="detail">
                    <strong>Email</strong>
                    <a href={`mailto:${cvData.personal.email}`}>{cvData.personal.email}</a>
                  </div>
                </li>
                <li>
                  <span class="icon">📱</span>
                  <div class="detail">
                    <strong>{currentLang() === 'es' ? 'Teléfono' : 'Phone'}</strong>
                    <a href={`tel:${cvData.personal.phone}`}>{cvData.personal.phone}</a>
                  </div>
                </li>
                <li>
                  <span class="icon">💼</span>
                  <div class="detail">
                    <strong>LinkedIn</strong>
                    <a href={`https://www.linkedin.com/in/${cvData.personal?.social?.linkedin || ''}`} target="_blank" rel="noopener">{currentLang() === 'es' ? 'Ver perfil' : 'View profile'}</a>
                  </div>
                </li>
                <li>
                  <span class="icon">💻</span>
                  <div class="detail">
                    <strong>GitHub</strong>
                    <a href={`https://github.com/${cvData.personal?.social?.github || ''}`} target="_blank" rel="noopener">@{cvData.personal?.social?.github || ''}</a>
                  </div>
                </li>
              </ul>
            </div>
            <div>
              <form onSubmit={handleSubmit}>
                <div class="field">
                  <label for="name" class="label">{currentLang() === 'es' ? 'Nombre *' : 'Name *'}</label>
                  <input 
                    id="name" 
                    value={formData().name}
                    onInput={(e) => setFormData({ ...formData(), name: e.target.value })}
                    type="text" 
                    class="input" 
                    required 
                  />
                </div>
                <div class="field">
                  <label for="email" class="label">Email *</label>
                  <input 
                    id="email" 
                    value={formData().email}
                    onInput={(e) => setFormData({ ...formData(), email: e.target.value })}
                    type="email" 
                    class="input" 
                    placeholder="tu@email.com" 
                    required 
                  />
                </div>
                <div class="field">
                  <label for="message" class="label">{currentLang() === 'es' ? 'Mensaje *' : 'Message *'}</label>
                  <textarea 
                    id="message" 
                    value={formData().message}
                    onInput={(e) => setFormData({ ...formData(), message: e.target.value })}
                    class="textarea" 
                    required 
                  />
                </div>
                <Show when={formStatus()}>
                  <div class={`alert ${formStatus().type}`}>{formStatus().message}</div>
                </Show>
                <button type="submit" class="btn" style={{ 'margin-top': '0.5rem' }} disabled={formLoading()}>
                  {formLoading() ? '⏳...' : (currentLang() === 'es' ? '📨 Enviar Mensaje' : '📨 Send Message')}
                </button>
              </form>
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer style={{ 'text-align': 'center', padding: '2rem 0', color: '#64748b', 'font-size': '0.85rem' }}>
          <p>© 2025 Eduardo Valenzuela — {currentLang() === 'es' ? 'Hecho con' : 'Built with'} 🔷 Solid</p>
          <p style={{ 'margin-top': '0.5rem' }}>
            <a href="/" style={{ 'margin-right': '1rem' }}>⚛️ React</a>
            <a href="/astro/" style={{ 'margin-right': '1rem' }}>⭐ Astro</a>
            <a href="/vue/" style={{ 'margin-right': '1rem' }}>💚 Vue</a>
            <a href="/vanilla/" style={{ 'margin-right': '1rem' }}>⚡ Vanilla</a>
            <a href="/next/">▲ Next.js</a>
          </p>
        </footer>
      </main>
    </>
  );
}

export default App;
