// frameworks/next/app/components/Footer.tsx
export function Footer({ name, t }: { name: string; t: (es: string, en: string) => string }) {
  return (
    <footer style={{ textAlign: 'center', padding: '2rem 0', color: '#64748b', fontSize: '0.85rem' }}>
      <p>© 2025 {name} — {t('Hecho con', 'Built with')} ▲ Next.js</p>
    </footer>
  );
}

export default Footer;

// frameworks/vue/src/components/Footer.vue
<template>
  <footer style="margin-top: 4rem; padding: 2rem 0; text-align: center; color: #64748b; font-size: 0.875rem;">
    <p>© {{ currentYear }} Eduardo Valenzuela — Construido con 💚 Vue</p>
  </footer>
</template>

<script>
export default {
  name: 'Footer',
  computed: {
    currentYear() {
      return new Date().getFullYear();
    }
  }
}
</script>
