// frameworks/react/src/components/Navbar.jsx
import { useState, useEffect } from 'react';
import { useTranslation } from '../hooks/useTranslation.js';
import { ThemeToggle } from './ThemeToggle.jsx';
import { LanguageToggle } from './LanguageToggle.jsx';

export function Navbar() {
  const [activeSection, setActiveSection] = useState('');
  const [isScrolled, setIsScrolled] = useState(false);
  const { t, currentLang } = useTranslation();

  const sections = [
    { id: 'about', label: t('sections.about'), icon: '👤' },
    { id: 'services', label: currentLang === 'es' ? 'Servicios' : 'Services', icon: '🚀' },
    { id: 'experience', label: t('sections.experience'), icon: '💼' },
    { id: 'education', label: currentLang === 'es' ? 'Educación' : 'Education', icon: '🎓' },
    { id: 'projects', label: t('sections.projects'), icon: '🎨' },
    { id: 'skills', label: t('sections.skills'), icon: '⚡' },
    { id: 'contact', label: t('sections.contact'), icon: '📧' },
  ];

  const frameworks = [
    { id: 'react', name: 'React', icon: '⚛️', url: '/', active: true },
    { id: 'astro', name: 'Astro', icon: '🪐', url: '/astro/' },
    { id: 'vue', name: 'Vue', icon: '💚', url: '/vue/' },
    { id: 'solid', name: 'Solid', icon: '🔷', url: '/solid/' },
    { id: 'vanilla', name: 'Vanilla', icon: '⚡', url: '/vanilla/' },
    { id: 'lab', name: 'Lab', icon: '🧪', url: '/lab/' },
  ];

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 100);
      
      // Detectar sección activa
      const scrollPosition = window.scrollY + 150;
      
      for (const section of sections) {
        const element = document.getElementById(section.id);
        if (element) {
          const { offsetTop, offsetHeight } = element;
          if (scrollPosition >= offsetTop && scrollPosition < offsetTop + offsetHeight) {
            setActiveSection(section.id);
            break;
          }
        }
      }
    };

    window.addEventListener('scroll', handleScroll);
    handleScroll(); // Initial check
    
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToSection = (id) => {
    const element = document.getElementById(id);
    if (element) {
      const offset = 80;
      const elementPosition = element.getBoundingClientRect().top;
      const offsetPosition = elementPosition + window.pageYOffset - offset;

      window.scrollTo({
        top: offsetPosition,
        behavior: 'smooth'
      });
    }
  };

  return (
    <nav 
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        isScrolled 
          ? 'bg-white/95 dark:bg-slate-900/95 backdrop-blur-lg shadow-lg' 
          : 'bg-white/80 dark:bg-slate-900/80 backdrop-blur-md'
      }`}
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* PRIMERA FILA: Menu de secciones */}
        <div className="flex items-center justify-between h-14 border-b border-slate-200 dark:border-slate-700/50">
          {/* Logo */}
          <button
            onClick={() => scrollToSection('hero')}
            className="text-xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent hover:scale-110 transition-transform"
          >
            👨‍💻
          </button>

          {/* Menu Desktop */}
          <div className="hidden md:flex items-center gap-1">
            {sections.map((section) => (
              <button
                key={section.id}
                onClick={() => scrollToSection(section.id)}
                className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-all hover:scale-105 ${
                  activeSection === section.id
                    ? 'bg-primary text-white shadow-md'
                    : 'text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800'
                }`}
                title={section.label}
              >
                <span className="mr-1.5">{section.icon}</span>
                <span className="hidden lg:inline">{section.label}</span>
              </button>
            ))}
          </div>

          {/* Menu Mobile - Dots */}
          <div className="md:hidden flex items-center gap-2">
            {sections.map((section) => (
              <button
                key={section.id}
                onClick={() => scrollToSection(section.id)}
                className={`w-2 h-2 rounded-full transition-all ${
                  activeSection === section.id
                    ? 'bg-primary w-8'
                    : 'bg-slate-300 dark:bg-slate-700'
                }`}
                title={section.label}
                aria-label={section.label}
              />
            ))}
          </div>

          {/* Controls: Theme + Language */}
          <div className="flex items-center gap-2">
            <ThemeToggle />
            <LanguageToggle />
          </div>
        </div>

        {/* SEGUNDA FILA: Framework switcher */}
        <div className="flex items-center justify-center h-10 gap-1 overflow-x-auto scrollbar-hide">
          {frameworks.map((fw) => (
            <a
              key={fw.id}
              href={fw.url}
              className={`px-3 py-1 rounded-md text-xs font-medium transition-all hover:scale-105 whitespace-nowrap ${
                fw.active
                  ? 'bg-gradient-to-r from-blue-600 to-purple-600 text-white shadow-md'
                  : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800'
              }`}
              title={`Ver en ${fw.name}`}
            >
              <span className="mr-1">{fw.icon}</span>
              <span className="hidden sm:inline">{fw.name}</span>
            </a>
          ))}
        </div>
      </div>
    </nav>
  );
}

// frameworks/vue/src/components/Navbar.vue
<template>
  <nav :class="{ light: theme === 'light' }">
    <div class="inner">
      <!-- FILA 1: Menu principal -->
      <div class="menu-row">
        <button class="logo-btn" @click="scrollToTop">
          👨‍💻
        </button>
        <div class="menu-links">
          <a href="#about"><span class="icon">👤</span><span>{{ currentLang === 'es' ? 'Sobre mí' : 'About' }}</span></a>
          <a href="#services"><span class="icon">🚀</span><span>{{ currentLang === 'es' ? 'Servicios' : 'Services' }}</span></a>
          <a href="#experience"><span class="icon">💼</span><span>{{ currentLang === 'es' ? 'Experiencia' : 'Experience' }}</span></a>
          <a href="#education"><span class="icon">🎓</span><span>{{ currentLang === 'es' ? 'Educación' : 'Education' }}</span></a>
          <a href="#projects"><span class="icon">🎨</span><span>{{ currentLang === 'es' ? 'Proyectos' : 'Projects' }}</span></a>
          <a href="#skills"><span class="icon">⚡</span><span>{{ currentLang === 'es' ? 'Habilidades' : 'Skills' }}</span></a>
          <a href="#contact"><span class="icon">📧</span><span>{{ currentLang === 'es' ? 'Contacto' : 'Contact' }}</span></a>
        </div>
        <div class="controls">
          <button class="theme-toggle" @click="$emit('toggleTheme')" :title="currentLang === 'es' ? 'Cambiar tema' : 'Toggle theme'">
            {{ theme === 'dark' ? '🌙' : '☀️' }}
          </button>
          <div class="lang-toggle">
            <button 
              :class="{ active: currentLang === 'es' }"
              @click="$emit('changeLang', 'es')"
            >
              ES
            </button>
            <button 
              :class="{ active: currentLang === 'en' }"
              @click="$emit('changeLang', 'en')"
            >
              EN
            </button>
          </div>
        </div>
      </div>

      <!-- FILA 2: Framework switcher -->
      <div class="frameworks-row">
        <a href="/" title="React version">⚛️ <span class="hidden-mobile">React</span></a>
        <a href="/astro/" title="Astro version">🪐 <span class="hidden-mobile">Astro</span></a>
        <a href="/vue/" title="Vue version" class="active">💚 <span class="hidden-mobile">Vue</span></a>
        <a href="/solid/" title="Solid version">🔷 <span class="hidden-mobile">Solid</span></a>
        <a href="/vanilla/" title="Vanilla JS version">⚡ <span class="hidden-mobile">Vanilla</span></a>
        <a href="/next/" title="Next.js version">▲ <span class="hidden-mobile">Next.js</span></a>
        <a href="/lab/" title="Sobre este proyecto">🧪 <span class="hidden-mobile">Lab</span></a>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'Navbar',
  props: {
    currentLang: {
      type: String,
      required: true
    },
    theme: {
      type: String,
      required: true
    }
  },
  emits: ['changeLang', 'toggleTheme'],
  methods: {
    scrollToTop() {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  }
};
</script>

<style scoped>
nav {
  position: sticky;
  top: 0;
  z-index: 50;
  backdrop-filter: blur(12px);
  background: rgba(15, 23, 42, 0.95);
  border-bottom: 1px solid rgba(148, 163, 184, 0.2);
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
}

nav.light {
  background: rgba(255, 255, 255, 0.95);
  border-bottom-color: rgba(203, 213, 225, 0.5);
}

.inner {
  max-width: 1100px;
  margin: 0 auto;
  padding: 0 1rem;
}

/* Primera fila: menu */
.menu-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 56px;
  border-bottom: 1px solid rgba(148, 163, 184, 0.15);
}

.logo-btn {
  background: transparent;
  border: none;
  cursor: pointer;
  font-size: 1.5rem;
  padding: 0;
  line-height: 1;
  transition: transform 0.2s;
}

.logo-btn:hover {
  transform: scale(1.1);
}

.menu-links {
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
}

.menu-links a {
  color: #cbd5e1;
  text-decoration: none;
  padding: 0.4rem 0.7rem;
  border-radius: 0.5rem;
  font-size: 0.85rem;
  transition: all 0.15s;
  white-space: nowrap;
  display: flex;
  align-items: center;
  gap: 0.4rem;
}

nav.light .menu-links a {
  color: #475569;
}

.menu-links a:hover {
  background: rgba(148, 163, 184, 0.15);
}

.menu-links a .icon {
  font-size: 1rem;
}

/* Segunda fila: frameworks */
.frameworks-row {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 40px;
  gap: 0.5rem;
  overflow-x: auto;
  scrollbar-width: none;
}

.frameworks-row::-webkit-scrollbar {
  display: none;
}

.frameworks-row a {
  color: #94a3b8;
  text-decoration: none;
  padding: 0.3rem 0.7rem;
  border-radius: 0.5rem;
  font-size: 0.8rem;
  transition: all 0.2s;
  white-space: nowrap;
  background: transparent;
  border: 1px solid rgba(148, 163, 184, 0.2);
}

.frameworks-row a:hover {
  background: rgba(148, 163, 184, 0.15);
  border-color: rgba(148, 163, 184, 0.4);
}

.frameworks-row a.active {
  background: linear-gradient(135deg, #3b82f6, #8b5cf6);
  color: white;
  border-color: transparent;
  box-shadow: 0 2px 8px rgba(59, 130, 246, 0.3);
}

/* Controls */
.controls {
  display: flex;
  gap: 0.5rem;
  align-items: center;
}

.lang-toggle {
  background: #1e293b;
  border: 1px solid rgba(148, 163, 184, 0.3);
  border-radius: 0.5rem;
  padding: 0.25rem;
  display: flex;
  gap: 0.25rem;
}

nav.light .lang-toggle {
  background: #e2e8f0;
  border-color: rgba(148, 163, 184, 0.4);
}

.lang-toggle button {
  background: transparent;
  border: none;
  color: #94a3b8;
  padding: 0.35rem 0.75rem;
  border-radius: 0.4rem;
  cursor: pointer;
  font-size: 0.85rem;
  transition: all 0.2s;
  font-weight: 500;
}

nav.light .lang-toggle button {
  color: #64748b;
}

.lang-toggle button.active {
  background: #3b82f6;
  color: white;
}

.lang-toggle button:hover:not(.active) {
  background: rgba(148, 163, 184, 0.15);
  color: #cbd5e1;
}

nav.light .lang-toggle button:hover:not(.active) {
  background: rgba(148, 163, 184, 0.2);
  color: #334155;
}

.theme-toggle {
  background: transparent;
  border: 1px solid rgba(148, 163, 184, 0.3);
  border-radius: 0.5rem;
  padding: 0.35rem 0.6rem;
  cursor: pointer;
  font-size: 1.1rem;
  transition: all 0.2s;
  display: flex;
  align-items: center;
  justify-content: center;
  line-height: 1;
}

.theme-toggle:hover {
  background: rgba(148, 163, 184, 0.15);
  border-color: rgba(148, 163, 184, 0.5);
}

/* Mobile hide text */
@media (max-width: 640px) {
  .hidden-mobile {
    display: none;
  }
  .menu-links span:not(.icon) {
    display: none;
  }
}
</style>
